scene_filter/filter: true
scene_filter/xmin: -1.0
scene_filter/xmax: 1.0
scene_filter/ymin: 0.0
scene_filter/ymax: 1.0
scene_filter/zmin: 0.0
scene_filter/zmax: 1.5
scene_filter/erase_plane: true
scene_filter/downsample: false
scene_filter/leaf_s: 0.01
scene_filter/keep_organized: true
scene_filter/change_frame: false
scene_filter/new_frame: vito_anchor
